### ISSUE TITLE
Shooter Regen

### ISSUE THREAD

**Issue by realjoshuau** [Team3256/Offseason_Bot_2024#36]
* Current PR for shooter regen is broken (not implemented properly w/ command scheduler)
* To create a backcurrent, create a control request of `VelocityTorqueCurrentFOC` and set the setpoint to 0. USE A DIFFERENT CONFIG SLOT and tune the P value until the back current looks good.

**Comment by ThatXliner** [comment]
Could you link the relevant Chief Delphi post?

**Comment by realjoshuau** [comment]
Not on Chief, but I'll link the email from the CTRE engineer.
