### ISSUE TITLE
Redo all commands

### ISSUE THREAD

**Issue by chaoticthegreat** [Team3256/Offseason_Bot_2024#5]
Redo the commands so it looks cleaner. Get rid of all new keywords and replace it from stuff from Commands. Within subsystems use this.run.

**Comment by ThatXliner** [comment]
Could you elaborate the last part? What do you mean by “use this.run”? Should the default command factory be defined in a run method for every subsystem?

**Comment by chaoticthegreat** [comment]
Idk what you want me to say. Use this.run for command factories within subsystems

**Comment by ThatXliner** [comment]
Ok got it.

**Comment by ThatXliner** [comment]
Ohh I just realized that factory method existed on the SubsystemBase
