### ISSUE TITLE
Fix rumble on final

### ISSUE THREAD

**Issue by realjoshuau** [Team3256/Offseason_Bot_2024#60]
Final bot rumble is broken since the configureLEDs function is gone, use a trigger & callback

**Comment by ThatXliner** [comment]
When is the rumble triggered? Or in which commit was configureLEDs removed?

**Comment by realjoshuau** [comment]
See `RobotContainer` on commit `bf5c241`. The configureLED is commented out, but the code is still functional.

**Comment by realjoshuau** [comment]
Don't reimplement the LED stuff for now, it's broken
