### ISSUE TITLE
Figure out zeroing issue

### ISSUE THREAD

**Issue by realjoshuau** [Team3256/Offseason_Bot_2024#67]
Zeroing is weird when autonomous starts on an angle - why?

**Comment by memori034** [comment]
@realjoshuau not exactly solved but the manual bs i'd have to do basically takes less than a second

**Comment by memori034** [comment]
think the problem is seed field rel

**Comment by memori034** [comment]
get detailed final pose data from trajectory, run azimuth command on teleop init
